- clean: ['~']
- link:
    ~/.dotfiles: ''
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.gitignore_global: gitignore_global
    ~/.gitconfig: gitconfig
    ~/.zsh: zsh/
    ~/.zshrc: zshrc
    ~/.inputrc: inputrc
    ~/.tmux.conf: tmux.conf
    ~/.iterm2: iterm2/
- shell:
  - [git submodule update --init --recursive, Installing submodules]
